services:
  _defaults:
    autowire: true
    autoconfigure: true
  AgilelabFrCaptchaBundle\:
    namespace: 'AgilelabFr\CaptchaBundle\'
    resource: '../src'
    exclude: '../{DependencyInjection,Kernel.php}'