# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Checks

on:
  push:
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          tools: composer

      - name: Run PHPStan (Static Analysis on the bundle)
        run: |
          # Install PHPStan if not installed
          composer require --dev phpstan/phpstan
          # Run PHPStan on the local bundle (../), with the custom configuration file (phpstan.neon)
          vendor/bin/phpstan analyse -c phpstan.dist.neon
  symfony5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, intl
          tools: composer, symfony

      - name: Create Symfony 5.4 project
        run: |
          composer create-project symfony/skeleton:^5 symfony-test-project
          cd symfony-test-project

      - name: Configure Composer to use local bundle
        run: |
          cd symfony-test-project
          composer config prefer-stable true
          composer config repositories.local '{"type": "path", "url": "../"}'
          composer clear-cache

      - name: Install the local version of the bundle
        run: |
          cd symfony-test-project
          composer require agilelab-fr/captcha-bundle:@dev --no-cache
          

  symfony6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl
          tools: composer, symfony

      - name: Create Symfony 6 project
        run: |
          composer create-project symfony/skeleton:^6 symfony-test-project
          cd symfony-test-project

      - name: Configure Composer to use local bundle
        run: |
          cd symfony-test-project
          composer config prefer-stable true
          composer config repositories.local '{"type": "path", "url": "../"}'
          composer clear-cache

      - name: Install the local version of the bundle
        run: |
          cd symfony-test-project
          composer require agilelab-fr/captcha-bundle:@dev --no-cache
          

  symfony7:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          tools: composer, symfony

      - name: Create Symfony 7 project
        run: |
          composer create-project symfony/skeleton:^7 symfony-test-project
          cd symfony-test-project

      - name: Configure Composer to use local bundle
        run: |
          cd symfony-test-project
          composer config prefer-stable true
          composer config repositories.local '{"type": "path", "url": "../"}'
          composer clear-cache

      - name: Install the local version of the bundle
        run: |
          cd symfony-test-project
          composer require agilelab-fr/captcha-bundle:@dev --no-cache